### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by notlimahrelyt** [jakewaldron/PlexEmail#1]
Set everything up using ReadMe.

First attempt to run script I received the following:

![screen shot 2015-03-19 at 9 02 53 pm](https://cloud.githubusercontent.com/assets/5624324/6744136/5375a32c-ce7b-11e4-86fc-54590842c7bb.png)

Running on OS X (10.10.2)

**Comment by jakewaldron** [comment]
Hi there.  Have you installed requests?

You need to run:

```
pip install requests
```

If you do not have pip, run this first:

```
easy_install pip
```

**Comment by notlimahrelyt** [comment]
Thank you.

I have installed and corrected that. I am now receiving this error:

![screen shot 2015-03-20 at 12 56 33 pm](https://cloud.githubusercontent.com/assets/5624324/6756483/9f95d166-cf00-11e4-9d7f-6d8a322f14b7.png)

**Comment by jakewaldron** [comment]
I think there was a bug introduced with the library filter.  It should be fixed with this file: https://raw.githubusercontent.com/jakewaldron/PlexEmail/master/scripts/plexEmail.py

Please try that script and let me know if it works!

**Comment by jakewaldron** [comment]
Believe this is fixed. Closing.

**Comment by simondsmason** [comment]
Can I reopen this issue?
