### ISSUE TITLE
[Feature Request] TV Episode - Aired Date

### ISSUE THREAD

**Issue by C9H13NO3** [jakewaldron/PlexEmail#10]
Air date for TV episodes.  I have tried to figure out from Plex Web app the required tag but thinking I may need to delve into the xml, as such thought I would ask in the interim if you already new details for it?

**Comment by jakewaldron** [comment]
Looks like we can get it from the DB through originally_available.  I'll look into adding this field this week.

**Comment by jakewaldron** [comment]
Added in v0.7.0.  Let me know how it works for you.

**Comment by C9H13NO3** [comment]
Brilliant cheers, tested it last night and works perfectly
