### ISSUE TITLE
[Feature Request] - Support Music

### ISSUE THREAD

**Issue by Mawuena** [jakewaldron/PlexEmail#13]
Hello,

First of all, awesome code, truely !
However never thought of adding a third part to the relases : Music ?
It's the only thing missing at this stage even though I know that most people (myself included) use Plex for TV & Movies mostly.

In any case, thanks for the contribution and sharing your code with us all !!

Sincerely,

Mawuena

**Comment by jakewaldron** [comment]
Hi there,

I'll look into what is needed and what information is needed.  Also not sure how best to organize it.  Should it be a bit like TV shows?  A section for New Artists, New Albums and New Songs?

I'll try to do this over the next month (very little time available to dedicate to updating this script).

**Comment by Mawuena** [comment]
Oh thank you very much for this.
And yes about the section organization, it should be like TV shows

Cordialement / Sincerely

Mawuena Seketeli
Sent From My Linux Phone

**Comment by jakewaldron** [comment]
It's still under development, but the initial version to support music can be found in the dev branch.  If you are willing to be a guinea pig, I would love any feedback/bug reports.  It currently supports new artists and new albums and I plan on modifying the layout a bit over the next week or two (i.e. adding track list to the album sections).

**Comment by Mawuena** [comment]
Just tested it and it works perfectly.
I have a cron that launches it weekly so I'll let you know of bugs and what
not as soon as I notices on but for now, it just workes like a charm !

Cordialement / Sincerely

Mawuena Seketeli

**Comment by Mawuena** [comment]
Sorry, spoke to fast.
Noticed that the new artist category doesn't show any pictures even though there is some in my plex server.
All the other sections work out perfectly !

**Comment by Mawuena** [comment]
And if possible to make the descriptions more readable with a little bit of _< br >_  here and there, it'd be perfect.

**Comment by jakewaldron** [comment]
Thanks for testing.  I just checked in a fix for the missing images and also checked in a change to add track lists to the albums.

**Comment by Mawuena** [comment]
Awesome, will be on the lookout for the new commit to test it out

**Comment by jakewaldron** [comment]
Oops, forgot to push my changes.  They should be in the dev branch now.

**Comment by Mawuena** [comment]
Just did and it seems to be working perfectly fine.
Will toy with it a little bit more and if I notice anything I'll let you know but don't think I will as it seems awesome now ! Definitely ready to be moved to the "master" branch

Next step would be to thing of an easy way to update or auto update or something (without having to redo all the config and what not).
Unless it's already done and I'm being a bit of a big dummy ?

**Comment by jakewaldron** [comment]
There's no good way to update the config file right now, except maybe doing a diff on yours and the new one and adding the new lines.  If you use your old one, it should still work with the new script file and it will use the new default values, so that is an option if you don't plan on customizing the new fields from the default.
