### ISSUE TITLE
Error with line 669

### ISSUE THREAD

**Issue by phairplay** [jakewaldron/PlexEmail#14]
Hi
Could you please help me with the following error
c:\Plexemail\scripts>python plexemail.py
Traceback (most recent call last):
  File "plexemail.py", line 669, in <module>
    cur.execute('SELECT machine_identifier FROM remote_servers     WHERE url LIKE "h
ttp://127.0.0.1%";')
sqlite3.DatabaseError: file is encrypted or is not a database

I have python 32bit installed and placed the sqlite file in your instructions in the correct folder.

**Comment by jakewaldron** [comment]
Hi there,

Sorry for the delay in response.  This looks like it could be a permissions issue or an issue with the config value for plex_data_folder.

Are you still having an issue with this?

**Comment by phairplay** [comment]
Hey,
Not a problem it was the python request I needed to install it via cmd admin.

Thanks you responding and for this tool it's brilliant :)
