### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by oowtfmate** [jakewaldron/PlexEmail#18]
Can someone help me with the installation process? Every time I try to run plexEmail.py, the cmd prompt pops up, spits out an error, and closes too quickly for me to read and see what's the issue.  Very new to this so please excuse my ignorance.

**Comment by ebright** [comment]
Start with exactly how you are running plexemail.py.  for one you should already be in the cmd prompt so it will not close if the program quits.

**Comment by jakewaldron** [comment]
I was able to help him get it installed on Reddit.
