### ISSUE TITLE
error using cloudinary

### ISSUE THREAD

**Issue by fferraro87** [jakewaldron/PlexEmail#2]
everything works but if i try to use cloudinary, when i start plexEmail.py i've this error : 
http://pastebin.com/Xj8GWAtp

i'm using latest version of plexEmail (0.5.4)

**Comment by jakewaldron** [comment]
Just tested again with Cloudinary and it is working for me.  Could you verify that these three fields are filled correctly?

upload_cloudinary_cloud_name = '{cloud name}'
upload_cloudinary_api_key = '{api key}'
upload_cloudinary_api_secret = '{api secret}'

**Comment by fferraro87** [comment]
Yes, i copy and paste from my cloudinary page, but i've to paste key inside '' right? So For example upload_cloudinary_cloud_name = 'username'

**Comment by jakewaldron** [comment]
Yep.  On this page: https://cloudinary.com/console did you click Reveal next to the API Secret?

So if your cloudinary page looks like this:

Cloud name: plexemailtest
API Key: 123456789012345
API Secret: ab56789CdE76yH54

Your settings would look like this:

upload_cloudinary_cloud_name = 'plexemailtest'
upload_cloudinary_api_key = '123456789012345'
upload_cloudinary_api_secret = 'ab56789CdE76yH54'

**Comment by fferraro87** [comment]
yes i reveal API secret on my console on cloudinary and paste my credentials like you, but it doesnt work. i dont know why

**Comment by jakewaldron** [comment]
Ok, after looking at the error closer it looks like authentication is working just fine.  It might be an issue with a specific file that is being uploaded.  Could you use this script: https://raw.githubusercontent.com/jakewaldron/PlexEmail/dev/scripts/plexEmail.py

It includes a couple debug statements that will give me the image location and info about the file.  Please give me the output after you run it.

**Comment by fferraro87** [comment]
ok thanks, this is new output 
http://pastebin.com/ij5Di68A

**Comment by jakewaldron** [comment]
It looks like it might be an issue with symbolic links.  I've made a small change that should get it working: https://raw.githubusercontent.com/jakewaldron/PlexEmail/dev/scripts/plexEmail.py

Please let me know if it works.

**Comment by fferraro87** [comment]
nothing to do...same error, this is pastebin
http://pastebin.com/T38eLC1w

**Comment by jakewaldron** [comment]
Hmm I'm stumped.  The only thing I notice is that the size of that image is really small, so I'm wondering if that might be the issue.  Could you upload the image found here:

/home/hd13/tafazzi87/.docker-conf/Library/Application Support/Plex Media Server/Metadata/Movies/f/d28948450938a7f27b94f72e8da19e8e01ce600.bundle/Contents/com.plexapp.agents.themoviedb/posters/7254a2de773ee1be41c70ddbb1256304d7eaff12

**Comment by fferraro87** [comment]
do you say to upload to cloudinary from web? yes i can upload it
EDIT : now it works...after that i upload manually that image, now i've no error...strange

**Comment by jakewaldron** [comment]
That's great to hear!  I wonder if it was some sort of issue with your IP + using the API instead of uploading through their site.
