### ISSUE TITLE
Freenas Install Errors

### ISSUE THREAD

**Issue by naq90** [jakewaldron/PlexEmail#24]
I followed the instructions you posted to install this on a freenas system, however when I try to run the application I get back: 

`Traceback (most recent call last):
  File "/PlexEmail/scripts/plexEmail.py", line 784, in <module>
    execfile(configFile,config)
 File "/PlexEmail/scripts/config.conf", line 372
    msg_notice = ''
             ^
`

I'm not sure what my error is.

**Comment by jakewaldron** [comment]
Looks like there was a missing bracket in the config file.  Please take the new file or add a } to line 371.

**Comment by naq90** [comment]
Thanks for your quick reply. I added the bracket but now get these errors:

```
Traceback (most recent call last):
File "/PlexEmail/scripts/plexEmail.py", line 1194, in <module>
   imageInfo = processImage(hash, imageInfo['thumb'], 'show', 0, 0)
File "/PlexEmail/scripts/plexEmail.py", line 381, in processImage
   shutil.copy(imgLocation, img)
File "/usr/local/lib/python2.7/shutil.py", line 119, in copy
   copyfile(src, dst)
File "/usr/local/lib/python2.7/shutil.py", line 83, in copyfile
   with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory:       
 '/usr/local/www/apache24/data/plexemail/images/61352061f9f61efe9d68f70596a0ce84f0436f47_fb7cb9384affcf74fdf37225028e62509e63e1a9.jpg'
```

`

**Comment by jakewaldron** [comment]
Does the following path exist?

/usr/local/www/apache24/data/plexemail/images/

Have you copied the contents of the web folder into /usr/local/www/apache24/data/plexemail?

**Comment by jakewaldron** [comment]
Looking at the instructions, these steps might be incorrect:

cp -R /PlexEmail/web/ /usr/local/www/apache24/data
mkdir /usr/local/www/apache24/data/plexemail

It should be:

mkdir /usr/local/www/apache24/data/plexemail
cp -R /PlexEmail/web/ /usr/local/www/apache24/data/plexemail

**Comment by naq90** [comment]
That worked perfectly, thanks! I have another question, however, I was wondering how to set up the webpage? I'm a bit of a novice when it comes to all this. Is there a specific url that I need to go to after executing the script. I clicked on "View this email in your browser" on the email but the url was x-webdoc://C2C317C2-20B3-42E6-BE8D-28527808B733/plexemail and my browser could not open it.

**Comment by jakewaldron** [comment]
I'm not very familiar with apache on FREENAS.  You'll need to verify that the web folder you have is set up properly to be served as a webpage.  Once you verify that, you just need to set the following in the config file:

web_domain = 'http://www.example.com' (of course replace with your domain)
web_path = 'plexemail' (this will be the path to reach the index.html file...i.e. this would be at http://www.example.com/plexemail
