### ISSUE TITLE
Cloudinary SSL?

### ISSUE THREAD

**Issue by SaskiFX** [jakewaldron/PlexEmail#31]
Would it be possible to have a flag to make the webpage/email generated by the script use https instead of http for the Cloudinary stuff? I tried the images it included and it looks like both http and https are usable.

Thanks!

**Comment by jakewaldron** [comment]
That should be easy enough.  I'll look into adding it in the next week or so once I find some time.

**Comment by jakewaldron** [comment]
Added this in the dev branch for now.  New option in the config file: upload_cloudinary_use_https

Let me know how it works if you get the chance and I will push it to the master branch.

**Comment by jakewaldron** [comment]
This is in the master branch.
