### ISSUE TITLE
Plex Web Links

### ISSUE THREAD

**Issue by LexusSpeed03** [jakewaldron/PlexEmail#35]
I had to merge my changes to the new version and compared files everything seems fine. However the VBS wont run with scheduled task anymore but will if use CMD and run the script. The second issue is the webpage weblinks are not working? If I click a poster it says media server not available?

**Comment by jakewaldron** [comment]
What browser are you using when clicking the links?  Firefox has an issue where it converts certain characters in the link and there is no way to fix it without breaking all other browsers.

**Comment by jakewaldron** [comment]
Only thing I can think of with the VBS is that python might not be setup correctly in environment variables?  When you call from the command line are you calling:

```
python plexEmail.py
```

Or something else?

**Comment by vanderboon** [comment]
Just installed this and got the same "Media server not available message" when clicking a media item link from the email.

I traced this to an incorrect server guid, looking in the script it pulls this from the DLNA database (com.plexapp.dlna.db), I disabled DLNA years ago so I'm assuming in the intervening period my server GUID has changed through re-install/upgrade etc.

I enabled DLNA and re-ran the script and the links worked fine, I assume re-enabling the DLNA updated the server GUID.  I've since re-disabled DLNA and the script continues to work.

**Comment by jakewaldron** [comment]
@vanderboon Good catch.  I don't know of any other way of automatically obtaining the GUID except from the DLNA DB.  I think I will have to add an option in the config file to manually set it.

**Comment by LexusSpeed03** [comment]
@jakewaldron Would love to get this back to working stopped using it cause could never figure it out lol.

**Comment by jakewaldron** [comment]
I have added a new option in the config file: plex_web_server_guid

You can now use this if you do not use DNLA.  The GUID can be found in the URL when browsing your server (the x's in this sample link): https://app.plex.tv/web/app#!/server/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/details/%2Flibrary%2Fmetadata%2F43268

Let me know how it works.

**Comment by LexusSpeed03** [comment]
@jakewaldron i am seeing images in the email? but i am seeing them on the site and all once add the GUID? Maybe I altered something while back when i made changes?

**Comment by jakewaldron** [comment]
@DereckR Sorry, I'm not quite following what you are asking.  Could you clarify further what you issue is with the latest code?

**Comment by LexusSpeed03** [comment]
@jakewaldron Its all golden now realized forgot one piece from the other config file. The new update works great with the links now.

Thanks,
Dereck
