### ISSUE TITLE
Error: unsupported operand type(s)

### ISSUE THREAD

**Issue by soundtrackgeek** [jakewaldron/PlexEmail#38]
I'm getting an error when sending emails:
Traceback (most recent call last):
  File "plexEmail.py", line 1330, in <module>
    duration = row[5]/1000
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

I believe it has something to do with my music library. Strange this is, it has worked fine the last few days.

**Comment by soundtrackgeek** [comment]
The only think I can think of is that I added an album with only 1 track which is 1:04:52. Maybe it can only do track length until 59:59?

**Comment by soundtrackgeek** [comment]
I tried deleting that album and my mail works again :)

**Comment by jakewaldron** [comment]
Thanks for that insight.  The current dev branch has a fix in it for this already, but I will see if this changes how it should be fixed.
