### ISSUE TITLE
[Feature Request] - BCC field

### ISSUE THREAD

**Issue by JamminR** [jakewaldron/PlexEmail#5]
Though I know the Plex release discussion has requested this several times, I'm making an official request - Add BCC to capabilities.
Though I know PlexEmail already includes ways to prevent each emailed person from seeing another, I wish to only send one email, and not use cloud hosting.
BCC would allow me to do this (send one email, attaching the images myself)

**Comment by jakewaldron** [comment]
Sorry for the delay.  This has been added in v0.6.1.  Please verify it works before I close this request.

**Comment by JamminR** [comment]
Thank you. Will likely be sometime weekend of 10/17, at worst, weekend
after that before i have time to thoroughly test.
