### ISSUE TITLE
Absolutely Lost

### ISSUE THREAD

**Issue by Jborn4christ** [jakewaldron/PlexEmail#54]
Lost at how to get this running. I have plex.py running, plexrequests, but can not figure this install out. Not a dev, but techie enough to get in trouble. Anyone able to give me a few minutes to get it running?

**Comment by jakewaldron** [comment]
Let us know what you have done so far and what problems that are currently blocking you from running the script.

**Comment by Jborn4christ** [comment]
I got it! Sorry for the long delay
