### ISSUE TITLE
QPython2

### ISSUE THREAD

**Issue by ghost** [jakewaldron/PlexEmail#56]
Hi there, perhaps you can point me in the right direction, when i install this on my QNAP, i get the below issue:

Command:
/opt/QPython2/bin/python2 /share/CACHEDEV1_DATA/.qpkg/PlexEmail/scripts/plexEmail.py

Error:
/opt/QPython2/bin/python2: error while loading shared libraries: libdl.so.2: wrong ELF class: ELFCLASS32

Am i missing some dependancies, both QPython and Git. 

Your assistance would be appreciated

**Comment by ghost** [comment]
Sorted, it was QPython version problem

**Comment by jakewaldron** [comment]
Closing as issue has been fixed.
