### ISSUE TITLE
Email not being generated when several movies added

### ISSUE THREAD

**Issue by Marcelofs1** [jakewaldron/PlexEmail#58]
I just have updated the config and plexEmail.py files with the most recent and found a couple issues
1 - If you have a large amount of items added recently, the email is not generated. I started reducing the number of days to look for (from 7 to 5) and then voilá, email generated
Web page was not created because the option is disabled in the config file.
Successfully sent 1 email(s)
Is there any limit on how many Movies, TV, Music can be added?

2 - I also noticed that the cron job in the Freenas is no longer working. I have found some references indicating that this new files have broken cron but unable to find anything more specific. 
I have PlexEmail running on a jail in my FreeNAS
FreeNAS-9.10.1-U2 
Platform    Intel(R) Atom(TM) CPU C2750 @ 2.40GHz
Memory  16328MB
System Time Thu Oct 27 18:49:16 CDT 2016
Does anyone knows how to fix both issues?

**Comment by Marcelofs1** [comment]
No response? Does anyone is also facing the same issue?

**Comment by jakewaldron** [comment]
Are you using Cloudinary or hosting images on your own web server?  If not using either of those, it probably is trying to attach the images directly to the email, which can easily cause the email to be too big to send if there is a large amount of items.

Can you post your cron job/errors that you are seeing?

**Comment by Marcelofs1** [comment]
Thanks Jake
Here is the error I got from cron
jexec: jail "plexmail" not found

The command that was working until last month: 
jexec plexemail python2.7 /PlexEmail/scripts/plexEmail.py

however I do have it as jail
JID  IP Address      Hostname                      Path
     1  -               comics                        /mnt/Server/jails/comics
     2  -               plex                          /mnt/Server/jails/plex
     3  -               plexemail                     /mnt/Server/jails/plexemail

For the images, I am hosting it in my server.

**Comment by jakewaldron** [comment]
For the email, do these settings look like this:

upload_use_cloudinary = False
web_enabled = True
email_use_web_images = True

For the cron job, it looks like you misspelled the jail name.  plexmail instead of plexemail.

**Comment by Marcelofs1** [comment]
Jake, just found something weird I haven't noticed before: The error log says "plemail" while the jail is "plexEmail" - I deleted the cron and added again and now seems ok. 
My guess is that when FreeNas updated last time somehow it get some error.

web_enabled = True - This have solved - thank you
I haven't have any error with the previous version of the script. When I have is as TRUE, the images does not appear on the email and my previous script was with FALSE and never experienced any failure (even with more than 100 movies on the mail). I guess I will keep that way then.

Once again, thank you so much.
