### ISSUE TITLE
[BUG] Line 353: TypeError: Could not guess image MIME subtype

### ISSUE THREAD

**Issue by lmb56** [jakewaldron/PlexEmail#6]
File "C:\PlexEmail\scripts\plexEmail.py", line 353, in sendMail
msgImage = MIMEImage(fp.read())
File "C:\Python27\lib\email\mime\image.py", line 43, in init
raise TypeError('Could not guess image MIME subtype')
TypeError: Could not guess image MIME subtype

I have in the script made a temporary workaround:

Earlier: msgImage = MIMEImage(fp.read())
Now: msgImage = MIMEImage(fp.read(),_subtype="png")

The issue could be due to some UTF-8 stuff. I may have the danish letters æ,ø,å in some of the naming of objects.

**Comment by jakewaldron** [comment]
Thanks for this report.  I've updated the code to fix this issue and will commit it sometime this week when I add a couple other fixes/features.

**Comment by jakewaldron** [comment]
Fixed in v0.7.0.
