### ISSUE TITLE
Help with setup

### ISSUE THREAD

**Issue by campNav** [jakewaldron/PlexEmail#63]
Hi Jake, 

First off, THANKS! This looks amazing and im very greatful you developed a windows version!

I am having problems with setup... this is what I've done so far:

1. I've installed py 2.7
2. Downladed: Windows - SQLite version 3.8.8.3 and put it in "C:\Python27\DLLs"
3. Downloaded the module for Python. pip install requests, **extracted the .tz.gz file and put that folder in "C:\Python27\Lib"** (not sure if i should have extracted or just put the .tar.gz file in Libs)
4. Downloaded the code and put it in "F:\PleX\PlexEmail-master"
5. changed the variables in the config file in "F:\PleX\PlexEmail-master\scripts" and set the following parameters:

```
- plex_data_folder = 'F:\\PleX\\'
- web_folder = '' (I left this blank because i dont have a web-folder (I assume this has something to do with cloud storage)
- plex_web_server_guid = 'a0c8b1ddcXXXXXXXXXXXXXXXXX6b5d4afdc7b99'
- logging_file_location = 'F:\\PleX\\' 
- plex_username = 'XXX' (hidden)
- plex_password = 'XXX' (hidden)
- email_to = ['MYEMAIL@gmail.com']
- email_username = 'MYEMAIL@gmail.com''
- email_password = '!@!@!@!@!@!'
```

All other parameters i left the same....

NOW: I restarted the computer, and when I run 'plexEmail.vbs' (double click) NOTHING HAPPENS!!! (No email to 'MYEMAIL@gmail.com')

It does not even create a log-file in the "logging_file_location" directory.

Any help is greatly appreciated.

**Comment by ajlanga** [comment]
I am having the same problem.  Any solution yet?

**Comment by jakewaldron** [comment]
Please make sure that the email_username is correct.  It appears to have two apostrophes at the end of the line.

email_username = 'MYEMAIL@gmail.com''

Something wrong in the config file would break the script before logging could start.  In cases like this it you can open the command prompt and run the script manually with:

    python plexEmail.py -t

This will thrown an exception and help pinpoint the issue.

**Comment by ajlanga** [comment]
I was able to fix the problem by getting rid of the apache installation as that seemed to break it for me whenever my FreeNAS box rebooted.  It's been working fine since doing this but can obviously not host the webpage with it but it does generate the email reliably.

**Comment by jakewaldron** [comment]
Closing.
