### ISSUE TITLE
Issues with PlexEmail setup

### ISSUE THREAD

**Issue by rnvntr** [jakewaldron/PlexEmail#64]
Hello, just installed wamp, python and replaced the files, Still not able to send emails. 
![capture](https://cloud.githubusercontent.com/assets/24457550/21013674/01226698-bd29-11e6-8900-a02ea0529398.PNG)

**Comment by shaqui** [comment]
you need to install requests $ pip install requests

**Comment by jakewaldron** [comment]
Closing as the solution has been provided.
