### ISSUE TITLE
GUID detection from config file

### ISSUE THREAD

**Issue by c360e5f1** [jakewaldron/PlexEmail#69]
I'm not a Python programmer, but I don't know if this is correct. On my setup, I don't use DLNA so I need to set the GUID of the server in the config file.

However, after some debugging, I found that the plexEmail script always tries to hit the DLNA server for the GUID and the value I put in the config file.

```
if (config['filter_include_plex_web_link']):
  if (config['plex_web_server_guid'] == ''):
    plexWebLink = 'http://plex.tv/web/app#!/server/' + config['plex_web_server_guid'] + '/details/%2Flibrary%2Fmetadata%2F'
```

Perhaps that comparison should be:
`if (config['plex_web_server_guid'] != ''):`

**Comment by jakewaldron** [comment]
Good catch.  Looks like this is broken (guess not too many people use this feature).  Will fix it for a future release.

**Comment by jakewaldron** [comment]
Fixed in dev branch

**Comment by jakewaldron** [comment]
Dev branch has now been merged into master.  Closing.
