### ISSUE TITLE
Everytime Task Scheduler runs the VBS file it keeps popping up  "use this program"

### ISSUE THREAD

**Issue by nafeasonto** [jakewaldron/PlexEmail#71]
The weekly run for the plexeamil is not working because when it comes to run the script, it pops up the windows to use the scripting program, and I don't see an option to "use this program all the time."  So it just sits there until i hit okay.

How do i get around this.

**Comment by carlosmg2** [comment]
same here but solved it creating a .cmd and schedule the execution of that .cmd instead of the .vb
The .cmd contains:
`Start C:\Python27\pythonw.exe "C:\Program Files (x86)\Plex\PlexEmail-master\scripts\plexEmail.py"`

**Comment by jakewaldron** [comment]
Closing this as carlosmg2 provided a solution.
