### ISSUE TITLE
Plex server on nvidia shield 

### ISSUE THREAD

**Issue by phairplay** [jakewaldron/PlexEmail#74]
Hi, 
I'm wanting to play 4K but my pc won't cope with it. Is it possible to run this script on my pc with the plex server on a nvidia shield?

All my content will remain on my NAS

**Comment by jakewaldron** [comment]
I'm not familiar with the Shield, but if you are able to have read/write
access to the databases in the Plex Media Server folder on the Shield (from
the user running the script), you should be able to have the script running
from another machine.

Does the shield have this folder on the internal storage that you can
access (it might be in /sdcard/)?

/Plex Media Server/Plug-in Support/Databases

**Comment by jakewaldron** [comment]
Closing this.  Please reopen if my suggestion did not work.

**Comment by Arcanemagus** [comment]
Android applications (such as the PMS server that runs on the SHIELD) have isolated private storage where things like the Database are stored, as such access like that wouldn't be possible from a remote machine.

**Comment by jakewaldron** [comment]
Thanks for the comment Arcanemagus.  So sadly, Phairplay, it looks like it will not be able to work on the Shield.
