### ISSUE TITLE
Corrupted Plex DB

### ISSUE THREAD

**Issue by make92** [jakewaldron/PlexEmail#8]
i tested your PlexEmail and initially everything looked great but then i started to get problems that my Plex library DB got corrupted.

any idea what exactly is causing that. as soon as i disabled PlexEmail the DB is stable

Matt

**Comment by morbidpete** [comment]
I had the same issue. I cause it thinking when i did my first test script, it took so long i force stopped it and corrupted the DB. I restored a back up. Did the same thing to verify that is in fact what corrupted it and same result. I now let it run its course :-P (daily DB backups help)

**Comment by make92** [comment]
What I figured out was that it o ly happened when I was using Plexemail in a Docker on my Unraid server.
Now it's running in a VM on Linux mint without any problems.

**Comment by jakewaldron** [comment]
I've made some changes around the DB usage in the dev branch.  It now properly closes connections and before opening the db files, it first makes a copy (and deletes the copy after closing the db connection).  This should prevent corruption issues in the future.

**Comment by jakewaldron** [comment]
Dev branch has been merged into master.  Closing.
