### ISSUE TITLE
Once Cron Triggers, The Script Keeps Running

### ISSUE THREAD

**Issue by slamanna212** [jakewaldron/PlexEmail#9]
The script ran 7 times and sent 7 emails to each user before i could stop it

Is there a special setup i have to do for the cron?

**Comment by jakewaldron** [comment]
Can you provide the cron job (specifically the timings of the job)?

**Comment by slamanna212** [comment]
I redid the crontab, and tested it, it seamed to work this time, this is
the working one

10 12 \* \* 4 /usr/bin/python /opt/PlexEmail/scripts/plexEmail.py
